apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: evvg0dwld-nodejs 
  janus-idp.io/tekton: evvg0dwld-nodejs
  backstage.io/kubernetes-id: evvg0dwld-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: evvg0dwld-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  