apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: evvg0dwld-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: evvg0dwld-nodejs 
  name: evvg0dwld-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: evvg0dwld-nodejs 
